[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g corepack@latest && corepack enable && corepack prepare pnpm@10.27.0 --activate && pnpm install"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm --filter @meteora-invent/scaffold/fun-launch start"
